export const data = [
  {
    id: 1,
    title: "name1",
    priority: 1,
    levelOfEffort: "low",
    client: "ardalan",
    status: "doing",
  },
  {
    id: 2,
    title: "name2",
    priority: 1,
    levelOfEffort: "low",
    client: "ardalan",
    status: "doing",
  },
  {
    id: 3,
    title: "name3",
    priority: 1,
    levelOfEffort: "low",
    client: "ardalan",
    status: "doing",
  },
  {
    id: 4,
    title: "name4",
    priority: 1,
    levelOfEffort: "low",
    client: "ardalan",
    status: "doing",
  },
  {
    id: 5,
    title: "name5",
    priority: 1,
    levelOfEffort: "low",
    client: "ardalan",
    status: "doing",
  },
];
